---
version: "3.7"

# This docker-compose file is used to build and test the container

secrets:
  postgres_password:
    file: ./src/secrets/postgres-password
  postgres_username:
    file: ./src/secrets/postgres-username

services:
  guacscanner:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    image: cisagov/guacscanner
    init: true
    secrets:
      - source: postgres_password
        target: postgres-password
      - source: postgres_username
        target: postgres-username

  guacscanner-version:
    # Run the container to collect version information
    image: cisagov/guacscanner
    init: true
    restart: "no"
    command: --version
